Add FOSSILIZE_REPLAY_WRAPPER env variable support.
ValveSoftware/Fossilize pull request #193
Opened 2022-06-03 22:48 UTC by d-riley

2022-06-06 11:10 UTC, HansKristian-Work commented
I'm not sure what problem this is intended to solve. Why not just invoke the wrapper directly?

2022-06-06 17:45 UTC, d-riley commented
I don't have access to modify the caller (ie Steam Client), and @Plagman said to just make the change here.

2022-06-07 15:06 UTC, HansKristian-Work requested changes

2022-06-07 17:37 UTC, moonfall commented on cli/fossilize_replay.cpp
> +        // If a wrapper is specified, pass execution entirely to the wrapper.
Done.

2022-06-07 17:37 UTC, moonfall commented on cli/fossilize_replay.cpp
> +        if (wrapper_path && *wrapper_path) {
Done.

2022-06-07 17:43 UTC, d-riley commented on cli/fossilize_replay.cpp
> +        // If a wrapper is specified, pass execution entirely to the wrapper.
Done. (Sorry for dup comments.)

2022-06-07 17:43 UTC, d-riley commented on cli/fossilize_replay.cpp
> +        if (wrapper_path && *wrapper_path) {
Done.

2022-06-08 09:42 UTC, merged