RFC: Document StreamArchive file format
ValveSoftware/Fossilize pull request #94
Opened 2020-09-04 15:52 UTC by aeikum

I know of a handful of implementations of this format, so we should formally define the format. A couple notes:

-The version was stored big-endian. Since the MS three bytes are currently zero, I've re-defined it to be one byte, with the upper three bytes unused. We could instead make it four big-endian bytes, if you like.

-I've defined the tag and hash sizes to be flexible. Together they must occupy 40 bytes, but the hash can be an application-defined length, with the tag taking up the remainder.

2020-09-14 14:25 UTC, HansKristian-Work commented on fossilize_db.cpp
> + * hash            unsigned char[hash_bytes]         Application-defined 'hash' to identify this entry. Stored as hexadecimal big-endian ASCII.
Endianness of the hash is technically application defined. It should be treated as 40 opaque hex values.

2020-09-14 14:27 UTC, HansKristian-Work requested changes
Sorry, didn't see this until now. Just a tiny nit, otherwise fine.

2020-09-14 14:39 UTC, HansKristian-Work commented
Another thing to mention is that the stream can be cut off anywhere and the last invalid entry should be considered to not exist.

2020-09-14 14:55 UTC, aeikum commented
Cool, good suggestions. I've pushed an update to fix those, and also mentions that tag+hash combos should be unique.

2020-09-17 08:02 UTC, HansKristian-Work approved these changes

2020-09-17 08:02 UTC, merged